name: Upload self-contained binaries

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write # for actions/upload-release-asset to upload release asset
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform: ["linux-amd64", "linux-arm64", "linux-s390x", "darwin-amd64", "darwin-arm64"]
        include:
          - os: ubuntu-18.04
            platform: "linux-amd64"
            pathsep: ":"
            asset_name: black_linux
            executable_mime: "application/x-executable"
          - os: ubuntu-18.04
            platform: "linux-arm64"
            pathsep: ":"
            asset_name: black_linux
            executable_mime: "application/x-executable"
          - os: ubuntu-18.04
            platform: "linux-s390x"
            pathsep: ":"
            asset_name: black_linux
            executable_mime: "application/x-executable"
          - os: macos-latest
            platform: "darwin-amd64"
            pathsep: ":"
            asset_name: black_macos
            executable_mime: "application/x-mach-binary"
          - os: macos-latest
            platform: "darwin-arm64"
            pathsep: ":"
            asset_name: black_macos
            executable_mime: "application/x-mach-binary"

    steps:
      - uses: actions/checkout@v3

      - name: Set up latest Python
        uses: actions/setup-python@v3
        with:
          python-version: "*"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install .
          python -m pip install pyinstaller

      - name: Build binary
        run: |
          python -m PyInstaller -F --name ${{ matrix.asset_name }} --add-data 'src/blib2to3${{ matrix.pathsep }}blib2to3' src/black/__main__.py

      - name: Upload binary as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: ${{ matrix.executable_mime }}